# Generated by Django 2.0.3 on 2018-12-09 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shape', models.CharField(max_length=255)),
                ('updatedate', models.DateTimeField(default=datetime.datetime.now)),
                ('createdon', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('total', models.IntegerField(default=56)),
                ('formsubmitted', models.IntegerField(default=66)),
                ('count', models.IntegerField(default=35)),
                ('createdon', models.DateTimeField(default=datetime.datetime.now)),
                ('lastupdated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('imageUrl', models.URLField(max_length=255)),
                ('updatedate', models.DateTimeField(default=datetime.datetime.now)),
                ('createdon', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
